Removes internal classes from javadoc generation
After some hacking and pondering the doclet is hard to maintain and to
evolve, it let internal links slip through.

On the other hand gradle javadoc task has its own quirks :

1. It works file by file, i.e. gradle feeds javadoc with a list of java
   source files, and thus disable some javadoc features like package
   linking.
2. gradle exclusion removes files from the file list fed to javadoc,
   as such javadoc emits errors and warning as it can't find these
   types, errors can be :

   * import org.mockito.internal.Internal <- error: package org.mockito.internal does not exists
   * import org.mockito.internal.Internal.util <- error: static import only from classes and interfaces
   * class Public extends Internal <- cannot find symbol
   * warning - Tag @linkplain: reference not found: org.mockito.internal.Internal internal stuff
   * warning - Tag @link: reference not found: org.mockito.stubbing

   Yet the javadoc is still generated without the missing types.

As the javadoc is still generated, this commits chose to *hide* the
javadoc errors and warning unless the gradle is run with the --info option.