Handle JVM internal error when mocking class triggers `NoClassDefFoundError` (#3499)
Mockito now throws Errors occurred during class initialization to callers
instead of swallowing it, and the JVM reporting an obscure exception.

Fixes #3498